Feat invite new users to a project that do not have an account yet
langfuse/langfuse pull request #574
Opened 2023-11-25 20:43 UTC by 18feb06

## What does this PR do?

Added new feature for inviting users to Langfuse by adding them to a project, even if they do not have an account yet.

Fixes #412 

 Loom Video: https://www.loom.com/share/cd05b806d9c84b2bb770106251731568?sid=ec6c1da8-6d7c-4cda-9e80-590abe0665f3

## Type of change

- [ x ] New feature (non-breaking change which adds functionality)

## Mandatory Tasks

- [ x ] Make sure you have self-reviewed the code. A decent size PR without self-review might be rejected.

## Checklist

2023-11-25 20:44 UTC, 18feb06 commented
Open to discussion

2023-11-26 05:25 UTC, marcklingen commented
This looks great @18feb06, thank you! I'll review tomorrow (it's a bit late right now here) and am excited to get this merged

2023-11-26 05:26 UTC, 18feb06 commented
no problem

2023-11-26 05:30 UTC, marcklingen commented
Do you prefer if I make small changes myself to get it merged tomorrow or rather written feedback?

2023-11-26 06:02 UTC, 18feb06 commented
I prefer getting feedback as it helps me to know my mistakes but you can do as you wish

2023-11-27 23:23 UTC, marcklingen requested changes
Thanks again, see my comments which are meant to be very actionable. Let me know if you have any questions!

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/server/projectMembersRouter.ts
> +      if (!project) throw new Error("Project not found");
When using findFirstOrThrow, it already throws if none is found. Better to use findFirst and throw error yourself like you did

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/server/projectMembersRouter.ts
> +        ctx.session.user.name ?? `${process.env.EMAIL_FROM_NAME}`,
Suggesting a change
- From name = EMAIL_FROM_NAME
- Title: {user.name} invited you to {project.name} -> can be done in sendProjectInvitation, you just need to pass both vars to the function

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/components/ProjectMembersTable.tsx
> +        &nbsp;Pending:
Rename to "Pending Invites" and hide it if there are no pending invites

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/components/CreateProjectMemberButton.tsx
> +        // @ts-expect-error (Due to unexpected error of ts)
Do not ts-ignore, use e.g. `"senderId" in result`

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/components/CreateProjectMemberButton.tsx
> +    <div>
use <></> for react fragment here, no need for div

2023-11-27 23:23 UTC, marcklingen commented on src/features/rbac/components/CreateProjectMemberButton.tsx
>          form.setError("email", {
let's display the actual errors here
- catch() - only console.error, do not form.setError
- use onError callback of mutCreateProjectMember to add the error state to the form with the real message. Check editDatasetItem for a reference implementation

2023-11-27 23:23 UTC, marcklingen commented on src/features/email/lib/project-invitation.ts
> +import { Resend } from "resend";
drop resend dependency

2023-11-27 23:23 UTC, marcklingen commented on src/features/email/lib/project-invitation.ts
> +      process.env.EMAIL_FROM_ADDRESS ?? "team_langfuse@langfuse.com";
Use env. instead of process env for zod-typed environments
`import { env } from "@/src/env.mjs"`

2023-11-27 23:23 UTC, marcklingen commented on src/features/email/lib/project-invitation.ts
> +  try {
Check if all required envs to send emails are set, if not, console.error and return. Do not throw an error, some users will not set up email sending.

2023-11-27 23:23 UTC, marcklingen commented on src/features/email/lib/project-invitation.ts
> +  try {
-> No need to have defaults anymore with ??

2023-11-27 23:23 UTC, marcklingen commented on src/features/email/templates/ProjectInvitation.tsx
> +export const projectInvitationTemplate = (
The template is a start but would need some work. I'd suggest to use a decent plain text email to get this merged and then create a new issue to add a nice html template.

2023-11-27 23:36 UTC, 18feb06 commented
Thanks for this thorough feedback.. Noted all of above... working on them.

2023-11-29 02:11 UTC, marcklingen commented
Thanks @18feb06, I made some final changes (feel free to check them out), excited to release this feature tomorrow, you can test it on https://staging.langfuse.com in the meantime

2023-11-29 02:11 UTC, marcklingen approved these changes

2023-11-29 02:17 UTC, merged

2023-12-26 14:41 UTC, khareyash05 commented
Hi @18feb06. I am actually trying this feature on my local repo but I receive no email. I am actually concerned about EMAIL ADDRESS and SMPT CONNECTION URL. With what values do I have to substitute that for?

2023-12-26 15:05 UTC, 18feb06 commented
@khareyash05 
EMAIL_FROM_ADDRESS: It is email address used as sender email address or from email address.
SMPT CONNECTION URL: This string is a connection string for your smtp server. You can check its syntax and other information [here](https://nodemailer.com/smtp/).

2023-12-26 15:06 UTC, 18feb06 commented
Tell me if you have any other query. I am happy to assist you. 😊

2023-12-26 15:07 UTC, khareyash05 commented
Really appreciate that!Thank you

2023-12-26 15:22 UTC, khareyash05 commented
@18feb06 Can I use Gmail's SMTP server as well ie. `smtp.gmail.com`?

2023-12-26 15:27 UTC, 18feb06 commented
@khareyash05 

> @18feb06 Can I use Gmail's SMTP server as well ie. `smtp.gmail.com`? I am sorry for asking basic questions. A bit new on that part

Yes you can use.

2023-12-26 16:53 UTC, khareyash05 commented
Worked! Thanks a lot

2023-12-26 17:14 UTC, 18feb06 commented
> Worked! Thanks a lot

No problem

2024-03-27 21:57 UTC, zoltan-fedor commented
@18feb06 and @marcklingen,

Unfortunately it seems that the `SMTP_CONNECTION_URL` of the `nodemailer` is not able to handle special characters (which are quite typical when using authentication with SMTP).

The nodemail team advises the use of the configuration object instead of the connection string, see https://github.com/nodemailer/nodemailer/issues/1332

2024-03-27 22:35 UTC, marcklingen commented
https://github.com/langfuse/langfuse/issues/1517